class EnvVariables:
    """
    Defines which keys we need to get from AWS Secrets Manager
    for each application. The secret has to be already created
    in AWS to be able to deploy
    Please keep Alphabetical Order
    """

    # App test.APi
    test_ng_api = [
        "Auth_Key",
        "ServicesApiClient__BaseAddress",
        "ServicesApiClient__TimeoutSeconds",
        "ServiceApiKey",
        "Datadog__key",
        "Datadog__url",
        "LegacyClient__BaseAddress",
        "LegacyClient__TimeoutSeconds",
        "CORS__0__PolicyName",
        "CORS__0__Origin",
        "UseMigrationProxy",
        "KMS__JpmCbmKeyId"
    ]

    # App test.APi.JPM.Mock
    test_ng_jpm_mock_api = [
        "Auth_Key",
        "ServicesApiClient__BaseAddress",
        "ServicesApiClient__TimeoutSeconds",
        "ServiceApiKey",
        "Datadog__key",
        "Datadog__url",
        "LegacyClient__BaseAddress",
        "LegacyClient__TimeoutSeconds",
        "CORS__0__PolicyName",
        "CORS__0__Origin",
        "UseMigrationProxy"
    ]

    # App test.Docusign.Api
    test_ng_docusign_api = [
        "MongoConnectionString",
        "NODE_ENV",
        "USER_ID",
        "API_ACCOUNT_ID",
        "INTEGRATION_KEY",
        "DS_OAUTH_SERVER",
        "SESSION_SECRET",
        "TARGET_ACCOUNT_ID",
        "REDIRECT_URI_HOME",
        "PORT_NUMBER",
        "PAYMENT_GATEWAY_ACCOUNT_ID",
        "PAYMENT_GATEWAY_NAME",
        "PAYMENT_GATEWAY_DISPLAY_NAME",
        "REDIRECT_URI",
        "JWTPrivateKey",
        "JPM_AVS_PROD_PEM",
        "SENDGRID_VALIDATION_API_KEY",
        "IS_PRODUCTION",
        "PLAID_CLIENT_ID",
        "PLAID_SECRET",
        "SENDGRID_API_KEY",
        "REMINDER_MINUTES",
        "EXPIRATION_MINUTES",
        "SEND_EMAILS",
        "AVS_ENTRIES_PASSWORD",
        "AVS_CERT_PASSWORD",
        "PROFILE_TEMPLATE_ID",
        "INDIVIDUAL_PROFILE_UPDATE_TEMPLATE_ID",
        "BANKING_TEMPLATE_ID",
        "BANKING_AVS_VALID_TEMPLATE_ID",
        "BANKING_AVS_INVALID_TEMPLATE_ID",
        "INDIVIDUAL_BANKING_UPDATE_TEMPLATE_ID",
        "INDIVIDUAL_BANKING_UPDATE_AVS_VALID_TEMPLATE_ID",
        "PROFILE_AND_BANKING_TEMPLATE_ID",
        "PROFILE_AND_BANKING_AVS_INVALID_TEMPLATE_ID",
        "PROFILE_AND_BANKING_AVS_VALID_TEMPLATE_ID",
        "INDIVIDUAL_PROFILE_AND_BANKING_UPDATE_TEMPLATE_ID",
        "INDIVIDUAL_PROFILE_AND_BANKING_UPDATE_AVS_VALID_TEMPLATE_ID",
        "SECURE_ACH_ENROLLMENT_TEMPLATE_ID",
        "SECURE_ACH_ENROLLMENT_AVS_VALID_TEMPLATE_ID",
        "AVS_RESULTS_GOOGLE_SHEET_ID",
        "LEADS_ENTRIES_GOOGLE_SHEET_ID",
        "PROFILE_AND_BANKING_ENROLLMENT_TEMPLATE_ID",
        "PROFILE_AND_BANKING_ENROLLMENT_AVS_VALID_TEMPLATE_ID",
        "INDIVIDUAL_ACH_ENROLLMENT_TEMPLATE_ID",
        "INDIVIDUAL_ACH_ENROLLMENT_AVS_VALID_TEMPLATE_ID",
        "OAUTH_REDIRECT",
        "BANKING_ASYNC_VALID_TEMPLATE_ID",
        "SENDGRID_VALIDATION_API_KEY",
        "WHITELISTED_DOMAIN_SHEET",
        "ZENDESK_API_KEY_DEV",
        "ZENDESK_API_KEY",
        "ZENDESK_DOMAIN",
        "ZENDESK_DOMAIN_DEV",
        "COMPLIANCELY_TOKEN",
        "INDIVIDUAL_BANKING_ASYNC_VALID_TEMPLATE_ID",
        "PROFILE_AND_BANKING_ASYNC_VALID_TEMPLATE_ID",
        "INDIVIDUAL_PROFILE_AND_BANKING_ASYNC_VALID_TEMPLATE_ID",
        "INDIVIDUAL_ACH_ENROLLMENT_ASYNC_VALID_TEMPLATE",
        "INDIVIDUAL_ACH_ENROLLMENT_ASYNC_INVALID_TEMPLATE",
        "PROFILE_ASYNC_VALID_TEMPLATE_ID",
        "INDIVIDUAL_PROFILE_ASYNC_VALID_TEMPLATE_ID",
        "PROFILE_ASYNC_INVALID_TEMPLATE_ID",
        "INDIVIDUAL_PROFILE_ASYNC_INVALID_TEMPLATE_ID",
        "SANCTIONS_API_KEY",
        "LOB_API_KEY",
        "TIN_CHECKS_SHEET",
    ]

    # App test.Admin.Api
    test_ng_admin_api = [
        "ServicesApiClient__BaseAddress",
        "ServicesApiClient__TimeoutSeconds",
        "CORS__0__PolicyName",
        "CORS__0__Origin",
        "ServiceApiKey",
        "Datadog__key",
        "Datadog__url",
        "Auth0__Domain",
        "Auth0__Audience",
        "ALLOWED_MANUAL_LOGIN_USERNAMES",
        "ALLOWED_MANUAL_LOGIN_TOKEN",
        "ALLOWED_MANUAL_LOGIN_IPS"
    ]

    # App test.Api.Notifications
    test_ng_notifications_api = [
        "ServicesApiClient__BaseAddress",
        "ServicesApiClient__TimeoutSeconds",
        "ServiceApiKey",
        "Datadog__key",
        "Datadog__url"
    ]

    # App test.Services.APi
    test_ng_services_api = [
        "ConnectionStrings__Postgres__Api",
        "ConnectionStrings__Postgres__Admin",
        "ConnectionStrings__Mongo__ConnectionString",
        "ConnectionStrings__Mongo__Database",
        "ConnectionStrings__S3__BucketName",
        "ConnectionStrings__SQS__QueueUrl",
        "ConnectionStrings__Redis",
        "Datadog__key",
        "Datadog__url",
        "AuthyApiKey",
        "Logging__LogLevel__Default",
        "Logging__LogLevel__Microsoft_AspNetCore",
        "ConnectionStrings__FileDotCom__BaseUrl",
        "ConnectionStrings__FileDotCom__ApiKey",
        "ConnectionStrings__S3__StaticBucketName",
        "ServiceApiKey",
        "SendGrid__ApiKey",
        "SanctionsIO__Enabled",
        "SanctionsIO__BaseUrl",
        "SanctionsIO__ApiKey",
        "SanctionsIO__Timeout",
        "SanctionsIO__MaximumRetries",
        "SanctionsIO__MinimumScore",
        "SanctionsIO__CacheLifetime",
        "KMS__JpmCbmKeyId",
        "MicrosoftGraph__TenantId",
        "MicrosoftGraph__ClientId",
        "MicrosoftGraph__CertificateName",
        "Lob__BaseUrl",
        "Lob__ApiKey",
        "ComplyAdvantage__Enabled",
        "ComplyAdvantage__BaseUrl",
        "ComplyAdvantage__Username",
        "ComplyAdvantage__Password",
        "ComplyAdvantage__SourceFormat",
        "ComplyAdvantage__ApiKeyCacheTimeInMinutes",
        "FrontendBaseUrl",
        "AWS_S3_CUSTOM_DOMAIN",
        "Column__ApiKey",
        "Column__BaseUrl",
        "IronPdf__LicenseKey",
        "PowerBI__ClientID",
        "PowerBI__ClientSecret",
        "PowerBI__TenantID",
        "Sentry__Dsn",
        "Sentry__TracesSampleRate",
        "Galileo__Url",
        "Galileo__apiLogin",
        "Galileo__apiTransKey",
        "Galileo__providerId",
        "Galileo__CardImageUrl",
        "Galileo__CardImageConfigId",
        "Galileo__PrnAccountNumber",
    ]

    # App test.Api.Portal
    test_ng_portal_api = [
        "Logging__LogLevel__Default",
        "Logging__LogLevel__Microsoft_AspNetCore",
        "Auth0__Domain",
        "Auth0__Audience",
        "ServicesApiClient__BaseAddress",
        "ServicesApiClient__TimeoutSeconds",
        "CORS__0__PolicyName",
        "CORS__0__Origin",
        "ServiceApiKey",
        "Datadog__key",
        "Datadog__url",
        "LegacyClient__BaseAddress",
        "LegacyClient__TimeoutSeconds",
        "IronPdf__LicenseKey",
        "CORS__1__PolicyName",
        "CORS__1__Origin",
        "UseMigrationProxy",
        "LegacyClientNodeApi__BaseAddress",
        "LegacyClientNodeApi__TimeoutSeconds",
        "ALLOWED_MANUAL_LOGIN_USERNAMES",
        "ALLOWED_MANUAL_LOGIN_TOKEN",
        "ALLOWED_MANUAL_LOGIN_IPS"
    ]
